### ISSUE TITLE
CLI upload fails shortly after "Storing file, hang tight!"

### ISSUE THREAD

**Issue by 1credit** [Storj/core#388]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
Storj@3.1.0
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior

Uploading of a ~1GB file should proceed smoothly.

```

```

### Actual Behavior

Waited until the day after 3.1.0 become available to validate, but still seeing the pre-3.1.0 behavior of file uploading aborting, without any error message, shortly after the "Storing file, hang tight!" message.
Screenshot below:

http://puu.sh/qU3kE/9dea770d4d.png

http://puu.sh/qU3mo/373f30c941.png

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by bookchin** [comment]
According to your `npm list storj` your global storj CLI installation is still 3.0.4. 

Run `npm install -g storj` and try again.

**Comment by 1credit** [comment]
Whoops, saw that core was good.  OK, now at storj 3.1.0 and still having the same problem.

http://puu.sh/qU5NU/498ad9241f.png

**Comment by aleitner** [comment]
This should be solved once all farmers have upgraded

**Comment by 1credit** [comment]
How many days should I wait before I test again.  "All" is a lot of farmers vs. "most".

**Comment by aleitner** [comment]
We're bumping the protocol in the next core release so you can see if who you are talking to is up to date or not.

**Comment by 1credit** [comment]
As of 9/1/2016 9:30am Central problem still occurs.  Note the program ends within seconds of the "Hang Tight!" message, well before any network timeout type event is likely to have occured.

**Comment by super3** [comment]
@1credit We will upgrade the bridge in the next few hours.

**Comment by 1credit** [comment]
Same issue as of 5:10pm Central.

**Comment by bookchin** [comment]
I don't think this one is related to network upgrade. But I cannot reproduce it. Is there anything you can tell us about the file you are uploading?

**Comment by 1credit** [comment]
903MB tar of a /var/spool/mail directory (thus the name mail.tar).

This shouldn't matter, and I'm hesitant to even mention it for fear of distraction, but the /tmp filesystem follows standard Unix security recommendations and is mounted nosuid, nodev, noexec.  Of those, noexec would only be an issue if Storj was trying to create some form of executable file there (chmod +x will fail), but I didn't see any evidence of that (see the /tmp directory screen shot above).

It is particularly worrisome that this process dies without ANY error message to the console.

**Comment by Th3Van** [comment]
After upgrading CLI and Bridge to the latest version, I managed to successfully upload a 10G file in about 36 min, using a storj CLI on Debian and `server025.storj.dk` as the bridge server. There was a few "Failed to transfer shard" but the bridge manage to find  an new shard holder, and everything seems to work out fine.

[Upload 10G file - Server025.storj.dk.txt](https://github.com/Storj/core/files/454337/Upload.10G.file.-.Server025.storj.dk.txt)

The 10G file are currently downloading while I'm writing this, but apparently it is taking a bit longer to download than uploading it.

On a side note:
I discovered that the upload sometimes may take a very long time, or it may even look like the upload has stopped. 
I started to see a small pattern that if this farmer `6735793f6e1041678aee205901fa7dc6548a10f6` (while it is using `108-90-22-140.lightspeed.cicril.sbcglobal.net`) are winning any/some of the shards from the bridge, the upload speed drops next to nothing, and I'll have to wait like 10-15 min. before the shards are uploaded and signed.

My guess is this particular farmer might be having a very bad IP route/bandwidth/pipe to the storj.dk servers, but might be better if using the api.storj.io servers, as they might be closer to this farmer.

The "problem" could be solved by using some sort of a reputation system, but an easier way to handle it would be to just "kicks" the farmer if the upload are going to take more than eg. 60 seconds. The client would then request a new farmer from the bridge server, and remember not to upload to this farmer again for some time.

---

The 10G file download didn't go so well  
```
 [Mon Sep 05 2016 06:07:39 GMT+0200 (CEST)] [info]   Received 6321405952 of 6442450944 bytes
 [Mon Sep 05 2016 06:07:39 GMT+0200 (CEST)] [info]   Received 6321537024 of 6442450944 bytes
 [Mon Sep 05 2016 06:07:39 GMT+0200 (CEST)] [info]   Received 6321668096 of 6442450944 bytes
 [Mon Sep 05 2016 06:07:41 GMT+0200 (CEST)] [warn]   Failed to download shard, reason: Unexpected end of source stream
 [Mon Sep 05 2016 06:07:41 GMT+0200 (CEST)] [error]  Failed to unlink partial file.
```

//Th3Van

**Comment by 1credit** [comment]
Thanks for the status Th3Van.  In my case, its not a matter of taking a long time, the command simply stops a few seconds after "Hang Tight!" and returns to the command prompt.

**Comment by 1credit** [comment]
Problem still exist with storj 3.1.1.

http://puu.sh/r2CqX/14bf772d1b.png

**Comment by 1credit** [comment]
Upgraded to storj 3.1.2 today and retried.  Progress!

Upon my normal upload, it failed with new error message "Concurrency cannot be less than 1".  Checked the script and it specified "-c3".  Changed that to "-c 3" and its now uploading.
